### ISSUE TITLE
Error on Android 9

### ISSUE THREAD

**Issue by kerbooo** [hansemannn/titanium-firebase-cloud-messaging#45]
Hello;
I am getting those errors from Google Play for Android 9 Devices.

 
```
java.lang.IllegalStateException: 
com.google.firebase.FirebaseApp.getInstance (Unknown Source:60)
com.google.firebase.iid.FirebaseInstanceId.getInstance (Unknown Source)
com.google.firebase.iid.FirebaseInstanceIdService.zza (Unknown Source:19)
com.google.firebase.iid.FirebaseInstanceIdService.handleIntent (Unknown Source:158)
com.google.firebase.iid.zzg.run (Unknown Source:26)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:784)
```
```

Huawei P20 (HWEML), Android 9

java.lang.RuntimeException: 
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3300)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3484)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:86)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2123)
android.os.Handler.dispatchMessage (Handler.java:109)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:7470)
java.lang.reflect.Method.invoke (Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)

Caused by: java.lang.NullPointerException: 
org.appcelerator.titanium.TiExceptionHandler.getError (TiExceptionHandler.java:100)
org.appcelerator.titanium.TiExceptionHandler.handleOpenErrorDialog (TiExceptionHandler.java:141)
org.appcelerator.titanium.TiExceptionHandler.openErrorDialog (TiExceptionHandler.java:121)
org.appcelerator.titanium.TiExceptionHandler.handleException (TiExceptionHandler.java:246)
org.appcelerator.kroll.KrollRuntime.dispatchException (KrollRuntime.java:540)
org.appcelerator.titanium.TiApplication$1.uncaughtException (TiApplication.java:365)
org.appcelerator.titanium.TiBaseActivity.onCreate (TiBaseActivity.java:677)
org.appcelerator.titanium.TiActivity.onCreate (TiActivity.java:22)
android.app.Activity.performCreate (Activity.java:7436)
android.app.Activity.performCreate (Activity.java:7426)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1286)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3279)
```

**Comment by m1ga** [comment]
Hi, when are you getting those errors? When a push arrives, when you click it or when you start your app?

**Comment by kerbooo** [comment]
Hello I am really have issue and I need help about this issue [https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141](https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141)

**Comment by m1ga** [comment]
@kerbooo please stop pushing the ticket in all the github issues. The tickets are here and people are already looking in your jira ticket and ask for feedback. So they are trying to help

**Comment by kerbooo** [comment]
OK. I am sorry but I did not find any solution since 2 months. I have tried so many things too.

**Comment by m1ga** [comment]
you didn't answer the questions above https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/45#issuecomment-453151643

**Comment by kerbooo** [comment]
When I upgraded my sdk to 7.5.1 That issue was fixed but now app did not work on android 9 devices. But it works on android 9 emulator. All details is in jira ticket about my specs.

**Comment by kerbooo** [comment]
Also when remove ti.ga module, app works on android 9 too. I have changed ti.ga module with firebase analaytics, I got similiar error. I think this issue about sdk but I can not resolve it

**Comment by lvdwiele** [comment]
I'm also can't run on a device when I have the core and cloudmessaging modules enabled, i see this error log:

(Samsung S8 Edge - Android 9)

```03-05 12:12:04.514 27111 27111 D AndroidRuntime: Shutting down VM
03-05 12:12:04.515 27111 27111 E AndroidRuntime: FATAL EXCEPTION: main
03-05 12:12:04.515 27111 27111 E AndroidRuntime: Process: nl.appmeesters.messagingapp, PID: 27111
03-05 12:12:04.515 27111 27111 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbo;
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6737)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6284)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6199)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:237)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7045)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbo" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/nl.appmeesters.messagingapp-c76OMo1cbfp7xutZeDHfLA==/base.apk"],nativeLibraryDirectories=[/data/app/nl.appmeesters.messagingapp-c76OMo1cbfp7xutZeDHfLA==/lib/arm64, /data/app/nl.appmeesters.messagingapp-c76OMo1cbfp7xutZeDHfLA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-05 12:12:04.515 27111 27111 E AndroidRuntime: 	... 12 more
03-05 12:12:04.516  5182  7925 D Debug   : !@DumpState : SHIP
03-05 12:12:04.517  5182  7925 D Debug   : !@DumpState : debug level:0x4f4c
03-05 12:12:04.517  5182  7925 D Debug   : !@Dumpstate : Finally, system will skip dumpstate```

**Comment by m1ga** [comment]
@lvdwiele can you please post your module versions

**Comment by lvdwiele** [comment]
I'm using:
Cloudmessaging: 1.4.0
Core: 3.0.2

I'm not using the Ti.Playservices because it worked without on android 8. But also tried to add this, which is version 11.0.40.

**Comment by m1ga** [comment]
you can't use it without. When it works without then you either have it installed globally (wrong version?) or other modules are include the play-service libraries (again, wrong version?). Playservice is included in the main SDK. So if you are trying to use 7.5.1.GA you have to force the 11.0.40 version of the ti.playservice module `<module version="11.0.40">...` otherwise it will use the latest global version

**Comment by lvdwiele** [comment]
I'm used 7.5.0.GA, but indeed moved to 7.5.1.GA, and also tried to force indeed 11.0.40.

Added `<module platform="android" version="11.0.40">ti.playservices</module>``` now (again to test).

Aaaaand it works :) Probably the previous try didn't go wel.

Thanks @m1ga !

**Comment by kerbooo** [comment]
My problem is about [https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141](https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141) and I did not solve it yet.

**Comment by hansemannn** [comment]
@kerbooo The issue you had was not related to the module but either with the ti.playservices version in your tiapp.xml (needs to be 11.0.40) or an issue with having multiple modules sharing playservices of different versions without using ti.playservices.

**Comment by kerbooo** [comment]
I have tried all version of ti.playservices and all version of modules. I tried so many combination. Appcelerator SDK too. Problem occurs when using ti.ga or firebase analytics together with firebase cloud messages. I have uploaded sample project on jira. Maybe you can try it.

**Comment by m1ga** [comment]
@kerbooo the demo project is incomplete:
* you didn't include `<module platform="android" version="11.0.40">ti.playservices</module>` 
* you didn't include `<module platform="android" >ti.ga</module>`
* what is fcm 1.5.0? The latest stable is 1.4.0 (which is inside the modules folder but the 1.5.0 will be used)

I don't have a Android 9 device so I just could test it on Android 7. The app doesn't open, it's frozen at the splash screen. If I remove the `ti.ga` module it works fine. So you should search there.

**Comment by kerbooo** [comment]
Yes as you said when I remove ti.ga app works. But I have tried to use firebase analytics instead of ti.ga module. But I am getting similiar issue with firebase analtics too. I create bug on ti.ga repo and I created here because of firebase analytics module error. Pelase somebody try above combination

firebase cloud message
firebase analytics
firebase core
appcelartor sdk 7.5.0GA or 7.5.1GA
ti.playservices
android 9 device not emulator

Above combination runs on Android > 9 devices. That does not run Android 9 devices only

I am sure that is bug. My opinion this error source is Appcelerator SDK. I have tried so many combinations versions or sdks.

**Comment by m1ga** [comment]
>  I wrote here because of firebase analytics module

but this is the issue tracker of cloud-messaging. I saw most of the tickets in different repos (ti.ga doesn't have a issue section) and the JIRA ticket. Not sure where to problem but you shouldn't mix errors in the repos

**Comment by kerbooo** [comment]
@m1ga thank you anyway

**Comment by m1ga** [comment]
But I hope it can be fixed somehow cause it looks like more people use that combination!

**Comment by kerbooo** [comment]
@kerbooo I think so too
